import { Inter } from "next/font/google"
import './globals.css'
import Header from '@/Component/Header'
import Providers from '@/Providers'
import Navbar from '@/Component/Navbar'
import SearchBox from '@/Component/SearchBox'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IMDb Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*  */}

      <body className={inter.className}>
        <Providers>
          <Header />
          <Navbar />
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  )
}
